apiVersion: apps/v1
kind: Deployment
metadata:
  name: classapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: classapp
  template:
    metadata:
      labels:
        app: classapp
    spec:
      containers:
      - name: classapp
        image: jassyboy/roadmapdevops:V1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
