apiVersion: apps/v1
kind: Deployment
metadata:
  name: classapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: classapp
  template:
    metadata:
      labels:
        app: classapp
    spec:
      containers:
      - name: classapp
        image: jassyboy/roadmapdevops:V1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: classapp
spec:
  type: NodePort
  selector:
    app: classapp
  ports:
  - port: 80
    targetPort: 80
    nodePort: 32000

